### ISSUE TITLE
getVariableCount

### ISSUE THREAD

**Issue by matts-dev** [JaysGitLab/cs-5666-scatt-brandy#18]

**Comment by fenwickjb** [comment]
Without description, it is hard to know exactly what you mean. But just for clarity sake, here is the issue I was going to add. If it's different in intent from your issue here, then make it a new issue...

Scratch allows for data "variables" that do what we programmers would expect: hold values for use by other scripts and/or sprites. Another issue counts the number of data-category blocks, but this issue is about knowing how many different variables are being defined. We could define a single data variable but then use it many times with many blocks. So the other issue would report many usages, but this issue would say only 1 data variable was defined/used.

Note that data variables can be created to be limited in their scope to a single sprite or available for all sprites. This is probably significant and we might want to know this in a disaggregated way.

**Comment by ghost** [comment]
Search for "Variables", define by " Open Sqwuiglies' "
